repos:
-  repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.4.0
   hooks:
   - id: flake8
-  repo: https://github.com/pre-commit/mirrors-mypy
   rev: v0.930
   hooks:
   - id: mypy
     exclude: conftest
     additional_dependencies:
        - 'sqlalchemy[mypy]'
        - 'types-python-dateutil'
        - 'types-pytz'
        - 'types-requests'
        - 'types-six'

