#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              - pip install pytest
              - pytest -v tests/* --junitxml=test-reports/report.xml
        - step:
            name: Lint code
            script:
              # Enforce style consistency across Python projects https://flake8.pycqa.org
              - pip install flake8
              - flake8 . --extend-exclude=dist,build --show-source --statistics
  branches:

    master:
      - step:
          name: "Deploy to Production"
          deployment: production
          script:
            - apt-get update && apt-get install -y zip
            - cd src && zip -r ../application.zip . && cd ..
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                APPLICATION_NAME: $APPLICATION_NAME
                COMMAND: 'all'
                ENVIRONMENT_NAME: $EB_PRODUCTION_ENV
                ZIP_FILE: 'application.zip'
                WAIT: 'true'
                S3_BUCKET: $EB_BUCKET