"""create admin page

Revision ID: 0f53bb639c8e
Revises: 
Create Date: 2023-05-02 17:06:41.183843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f53bb639c8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_admins',
    sa.Column('admin_username', sa.String(length=100), nullable=False),
    sa.Column('admin_password', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_admins')
    # ### end Alembic commands ###
