"""create withdrawal page

Revision ID: 601d40b40c9e
Revises: f39f170cd493
Create Date: 2023-05-20 13:13:57.132349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601d40b40c9e'
down_revision = 'f39f170cd493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('withdraw',
    sa.Column('summa', sa.String(length=155), nullable=False),
    sa.Column('agent_source_id', sa.String(length=100), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['agent_source_id'], ['loan_admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('withdraw')
    # ### end Alembic commands ###
