"""update admin page

Revision ID: b39cbc8a5794
Revises: 0f53bb639c8e
Create Date: 2023-05-02 18:07:52.397791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b39cbc8a5794'
down_revision = '0f53bb639c8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan_admins', sa.Column('is_login', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_admins', 'is_login')
    # ### end Alembic commands ###
