"""create admin page

Revision ID: f39f170cd493
Revises: 13b8776f56e6
Create Date: 2023-05-04 18:38:08.749154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f39f170cd493'
down_revision = '13b8776f56e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earnings_model', sa.Column('currency', sa.String(length=25), nullable=True))
    op.add_column('sources_of_income', sa.Column('percent', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources_of_income', 'percent')
    op.drop_column('earnings_model', 'currency')
    # ### end Alembic commands ###
