"""create admin page

Revision ID: f4a4c76a6e68
Revises: f39f170cd493
Create Date: 2023-05-17 18:06:23.137326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a4c76a6e68'
down_revision = 'f39f170cd493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdraw', 'time_created')
    # ### end Alembic commands ###
